kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: testabc-nginx-deployment
  labels:
    app: testabc-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testabc-nginx
  template:
    metadata:
      labels:
        app: testabc-nginx
    spec:
      containers:
      - name: testabc-nginx
      image: nginx:1.7.9
      ports:
      - containerPort: 80
